# On part d'un Linux vide avec Python
FROM python:3.10-slim

# On se place dans un dossier /app
WORKDIR /app

# On copie la liste des courses
COPY requirements.txt .

# On installe les librairies
RUN pip install --no-cache-dir -r requirements.txt

# On copie tout le reste du code (dont frontend.py)
COPY . .

# On dit à Docker de lancer Streamlit en utilisant le port fourni par le Cloud
CMD ["sh", "-c", "streamlit run frontend.py --server.port ${PORT:-8501} --server.address 0.0.0.0"]