events {}

http {
    # 🛡️ RATE LIMITING
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=2r/s;

    server {
        listen 80;

        # 🕵️ LA PORTE SECRÈTE (Appelée uniquement par Nginx, invisible pour les clients)
        location = /verify_admin {
            internal;
            proxy_pass http://api:80/verify_admin;
            proxy_pass_request_body off; # Nginx n'envoie pas le texte de la review, juste les headers (la clé API)
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

        # 🚀 ROUTE TRÈS PROTÉGÉE : La prédiction
        location /predict {
            # 1. Anti-spam
            limit_req zone=api_limit burst=5 nodelay;

            # 2. Vérification du rôle Admin ! (Si /verify_admin dit non, Nginx bloque ici)
            auth_request /verify_admin;

            # 3. Si tout est OK, on passe à la prédiction
            proxy_pass http://api:80/predict;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 🚪 AUTRES ROUTES : Login, Token, Docs (accessibles à tous)
        location / {
            proxy_pass http://api:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}