# 1. On part d'un Python léger
FROM python:3.12-slim

# 2. Dossier de travail
WORKDIR /app

# 3. Installation des dépendances (Streamlit, requests, etc.)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. On copie le code
COPY . .

# 5. On lance Streamlit en l'exposant vers l'extérieur
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]